name: dart_swapi
description: A Dart plugin implementation of the SWAPI (The Star Wars API)
homepage: https://github.com/thelabs-dev/dart_swapi
version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.0+4

dev_dependencies:
  test: ^1.0.0